import R2105DLeanActualLiAbelWeight.ActualLiAbelWeight

#check R2105DLeanActualLiAbelWeight.liPhaseNormalFormDeriv
#check R2105DLeanActualLiAbelWeight.liAbelPrimitive
#check R2105DLeanActualLiAbelWeight.liAbelWeight
#check R2105DLeanActualLiAbelWeight.liBoundaryResidualIntegrand
#check R2105DLeanActualLiAbelWeight.hasDerivAt_li_phase_normal_form
#check R2105DLeanActualLiAbelWeight.hasDerivAt_li_abel_primitive
#check R2105DLeanActualLiAbelWeight.li_abel_weight_eq
#check R2105DLeanActualLiAbelWeight.li_phase_normal_form_zero_left
#check R2105DLeanActualLiAbelWeight.li_phase_normal_form_zero_right
#check R2105DLeanActualLiAbelWeight.ActualLiAbelWeightWitness
#check R2105DLeanActualLiAbelWeight.actualLiAbelWeightWitness

#print axioms R2105DLeanActualLiAbelWeight.hasDerivAt_li_phase_normal_form
#print axioms R2105DLeanActualLiAbelWeight.hasDerivAt_li_abel_primitive
#print axioms R2105DLeanActualLiAbelWeight.li_abel_weight_eq
#print axioms R2105DLeanActualLiAbelWeight.li_phase_normal_form_zero_left
#print axioms R2105DLeanActualLiAbelWeight.li_phase_normal_form_zero_right
