import R2088DLeanEndpointFirstConcreteObligationActualLiKernelSourceDischarge.EndpointFirstConcreteObligationActualLiKernelSourceDischarge

namespace R2088DLeanEndpointFirstConcreteObligationActualLiKernelSourceDischarge

#check ActualLiKernelSourceEvidence
#check ActualLiKernelSourceEvidence.mk
#check actual_li_kernel_registered_from_source_evidence

end R2088DLeanEndpointFirstConcreteObligationActualLiKernelSourceDischarge
