import R2083DLeanEndpointFirstConcreteObligationEndpointTheoremConditionalFinalization.EndpointFirstConcreteObligationEndpointTheoremConditionalFinalization

namespace R2083DLeanEndpointFirstConcreteObligationEndpointTheoremConditionalFinalization

#check EndpointTheoremConditionalFinalizationStatement
#check endpoint_first_concrete_obligation_endpoint_theorem_conditional_finalization_statement_proved
#check endpoint_first_concrete_obligation_endpoint_theorem_conditional_finalization_from_exported_certificate
#check endpoint_first_concrete_obligation_endpoint_theorem_conditional_finalization_preserves_certificate_statement

end R2083DLeanEndpointFirstConcreteObligationEndpointTheoremConditionalFinalization
