import R2083DLeanEndpointFirstConcreteObligationEndpointTheoremConditionalFinalization.EndpointFirstConcreteObligationEndpointTheoremConditionalFinalization

namespace R2083DLeanEndpointFirstConcreteObligationEndpointTheoremConditionalFinalization

def endpoint_theorem_conditional_finalization_bridge_to_actual_li_target :=
  @endpoint_first_concrete_obligation_endpoint_theorem_conditional_finalization_from_exported_certificate

def endpoint_theorem_conditional_finalization_bridge_preserves_certificate_statement :=
  @endpoint_first_concrete_obligation_endpoint_theorem_conditional_finalization_preserves_certificate_statement

end R2083DLeanEndpointFirstConcreteObligationEndpointTheoremConditionalFinalization
