import R1961DLeanPacket
import R1962DLeanAnalyticRealization
import R1963DLeanAnalyticDecomposition
import R1964DLeanAnalyticMicroTargets
import R1965DLeanRealizationInterfaces
import R1966DLeanSourceCategories
import R1967DLeanSourceEvidence
import R1968DLeanAnchorClassification
import R1969DLeanFormalizationPriority
import R1970DLeanFirstFormalizationTarget
import R1971DLeanAbelBoundarySkeleton
import R1972DLeanToyAbelModel
import R1973DLeanFiniteAbelIdentity
import R1974DLeanFiniteAbelComponents
import R1975DLeanFiniteAbelNormalization
import R1976DLeanFiniteAbelEstimateGates
import R1977DLeanEstimateDependencyClosure
import R1978DLeanQuantitativeEstimateMatrix
import R1979DLeanConcreteEstimateBlueprint
import R1980DLeanConcreteEstimateStatements
import R1981DLeanConcreteProofSkeletons
import R1982DLeanProofObligationExecutionPlan
import R1983DLeanMainManuscriptAnchoredVerificationSpine
import R1984DLeanManuscriptObligationImplementationQueue
import R1985DLeanEndpointFirstImplementationBlock
import R1986DLeanEndpointStatementGroup
import R1987DLeanEndpointProofKernelInterface
import R1988DLeanEndpointKernelAxiomBoundary
import R1989DLeanEndpointConcreteLemmaStubs
import R1990DLeanEndpointConcreteLemmaStatementBank
import R1991DLeanEndpointConcreteProofRouteBank

open R1949DLean
open R1952DLeanSupport
open R1954DLeanBridge
open R1955DLeanScaffold
open R1956DLeanInterface
open R1957DLeanCoverage
open R1958DLeanAudit
open R1959DLeanTransfer
open R1960DLeanLimit
open R1961DLeanPacket
open R1962DLeanAnalyticRealization
open R1963DLeanAnalyticDecomposition
open R1964DLeanAnalyticMicroTargets
open R1965DLeanRealizationInterfaces
open R1966DLeanSourceCategories
open R1967DLeanSourceEvidence
open R1968DLeanAnchorClassification
open R1969DLeanFormalizationPriority
open R1970DLeanFirstFormalizationTarget
open R1971DLeanAbelBoundarySkeleton
open R1972DLeanToyAbelModel
open R1973DLeanFiniteAbelIdentity
open R1974DLeanFiniteAbelComponents

open R1975DLeanFiniteAbelNormalization
open R1976DLeanFiniteAbelEstimateGates
open R1977DLeanEstimateDependencyClosure
open R1978DLeanQuantitativeEstimateMatrix
open R1979DLeanConcreteEstimateBlueprint
open R1980DLeanConcreteEstimateStatements
open R1981DLeanConcreteProofSkeletons
open R1982DLeanProofObligationExecutionPlan
open R1983DLeanMainManuscriptAnchoredVerificationSpine
open R1984DLeanManuscriptObligationImplementationQueue
open R1985DLeanEndpointFirstImplementationBlock
open R1986DLeanEndpointStatementGroup
open R1987DLeanEndpointProofKernelInterface
open R1988DLeanEndpointKernelAxiomBoundary
open R1989DLeanEndpointConcreteLemmaStubs
open R1990DLeanEndpointConcreteLemmaStatementBank
open R1991DLeanEndpointConcreteProofRouteBank
#check R1949DLean.conditional_main_no_escape_from_all_obligations
#check R1949DLean.conditional_kill_attempt_forces_terminal_extension
#check R1952DLeanSupport.version_map_declares_unmodified_verified_core
#check R1952DLeanSupport.r1952_conditional_main_no_escape_from_verified_core
#check R1952DLeanSupport.r1952_conditional_terminal_extension_from_verified_core
#check R1954DLeanBridge.bridge_version_declares_inherited_verified_support
#check R1954DLeanBridge.bridge_conditional_no_escape_to_standard_conclusion
#check R1954DLeanBridge.bridge_conditional_kill_attempt_to_standard_conclusion
#check R1955DLeanScaffold.r1955_version_declares_intermediate_refined_scaffold
#check R1955DLeanScaffold.standard_li_scaffold_ready_unpacks
#check R1955DLeanScaffold.manuscript_analytic_scaffold_ready_unpacks
#check R1955DLeanScaffold.refined_bridge_conditional_no_escape_to_standard_conclusion
#check R1955DLeanScaffold.refined_bridge_conditional_kill_attempt_to_standard_conclusion
#check R1956DLeanInterface.r1956_version_declares_preformal_analytic_interface
#check R1956DLeanInterface.analytic_estimate_slots_declared
#check R1956DLeanInterface.estimate_slots_are_pending_formalization_examples
#check R1956DLeanInterface.mathlib_anchors_declared_external
#check R1956DLeanInterface.interface_obligation_table_has_all_labels
#check R1956DLeanInterface.interface_projection_records_refined_targets
#check R1956DLeanInterface.analytic_interface_assembles_refined_bridge_axioms
#check R1956DLeanInterface.analytic_interface_conditional_no_escape_to_standard_conclusion
#check R1956DLeanInterface.analytic_interface_conditional_kill_attempt_to_standard_conclusion
#check R1957DLeanCoverage.r1957_version_declares_interface_coverage_certification_layer
#check R1957DLeanCoverage.every_interface_obligation_has_refined_target
#check R1957DLeanCoverage.every_estimate_slot_has_interface_coverage
#check R1957DLeanCoverage.every_mathlib_anchor_is_declared_external_and_covered
#check R1957DLeanCoverage.r1957_declares_no_full_analytic_formalization
#check R1957DLeanCoverage.analytic_interface_no_escape_profile_records_complete_interface
#check R1957DLeanCoverage.analytic_interface_kill_attempt_profile_records_complete_interface
#check R1957DLeanCoverage.analytic_interface_theorems_use_only_declared_interface_axioms
#check R1957DLeanCoverage.analytic_interface_theorems_do_not_claim_full_analytic_formalization
#check R1957DLeanCoverage.toy_interface_coverage_certificate_runs
#check R1957DLeanCoverage.toy_interface_coverage_no_escape_still_reaches_standard_conclusion
#check R1957DLeanCoverage.toy_interface_coverage_terminal_extension_still_reaches_standard_conclusion
#check R1958DLeanAudit.r1958_version_declares_audit_certification_layer
#check R1958DLeanAudit.theorem_audit_ledger_records_declared_paths
#check R1958DLeanAudit.analytic_assumption_ledger_matches_inherited_interface
#check R1958DLeanAudit.pending_formalization_ledger_records_external_targets
#check R1958DLeanAudit.no_orphan_interface_obligations_are_audited
#check R1958DLeanAudit.no_orphan_estimate_slots_are_audited
#check R1958DLeanAudit.no_orphan_mathlib_anchors_are_externalized_and_audited
#check R1958DLeanAudit.no_orphan_refined_targets_are_audited
#check R1958DLeanAudit.no_hidden_dependency_audit_is_declared
#check R1958DLeanAudit.non_claim_ledger_lists_major_external_analytic_targets
#check R1958DLeanAudit.r1958_declares_no_full_analytic_formalization_claim
#check R1958DLeanAudit.toy_audit_certificate_runs
#check R1958DLeanAudit.toy_audit_no_escape_still_reaches_standard_conclusion
#check R1958DLeanAudit.toy_audit_terminal_extension_still_reaches_standard_conclusion
#check R1959DLeanTransfer.same_scale_target_transfer
#check R1959DLeanTransfer.same_scale_target_equivalence
#check R1959DLeanTransfer.no_hidden_normalization_target_transfer
#check R1959DLeanTransfer.no_hidden_normalization_target_equivalence
#check R1959DLeanTransfer.finite_to_abel_target_transfer
#check R1959DLeanTransfer.finite_to_abel_target_equivalence
#check R1959DLeanTransfer.finite_to_abel_no_hidden_normalization_transfer
#check R1959DLeanTransfer.finite_to_abel_no_hidden_normalization_equivalence
#check R1959DLeanTransfer.r1959_critical_slots_are_inherited_from_r1956_interface
#check R1959DLeanTransfer.r1959_transfer_depth_certificate_records_actual_abstract_theorems
#check R1959DLeanTransfer.r1959_transfer_layer_keeps_r1958_non_claim_boundary
#check R1959DLeanTransfer.toy_same_scale_transfer_runs
#check R1959DLeanTransfer.toy_finite_to_abel_transfer_runs
#check R1959DLeanTransfer.toy_no_hidden_normalization_transfer_runs
#check R1959DLeanTransfer.toy_finite_to_abel_no_hidden_normalization_transfer_runs
#check R1959DLeanTransfer.r1959_version_declares_same_scale_transfer_layer
#check R1960DLeanLimit.same_scale_boundary_limit_transfer
#check R1960DLeanLimit.eventual_finite_target_to_boundary_target
#check R1960DLeanLimit.no_hidden_scale_drift_boundary_transfer
#check R1960DLeanLimit.finite_to_abel_boundary_limit_transfer
#check R1960DLeanLimit.finite_to_abel_no_hidden_boundary_limit_transfer
#check R1960DLeanLimit.boundary_limit_uses_r1959_same_scale_transfer_on_tail
#check R1960DLeanLimit.r1960_critical_slots_are_inherited_from_r1956_interface
#check R1960DLeanLimit.r1960_limit_depth_certificate_records_actual_abstract_theorems
#check R1960DLeanLimit.r1960_limit_layer_keeps_r1958_non_claim_boundary
#check R1960DLeanLimit.toy_boundary_limit_passage_runs
#check R1960DLeanLimit.toy_finite_to_abel_boundary_limit_passage_runs
#check R1960DLeanLimit.toy_no_hidden_scale_drift_boundary_passage_runs
#check R1960DLeanLimit.toy_finite_to_abel_no_hidden_boundary_limit_passage_runs
#check R1960DLeanLimit.r1960_version_declares_abel_boundary_limit_layer
#check R1961DLeanPacket.explicit_packet_balance_to_target
#check R1961DLeanPacket.no_hidden_residual_packet_transfer
#check R1961DLeanPacket.controlled_prime_zero_endpoint_packets_to_li_target
#check R1961DLeanPacket.abel_boundary_yields_all_packet_controls
#check R1961DLeanPacket.abel_boundary_packet_balance_to_li_target
#check R1961DLeanPacket.finite_tail_boundary_packet_balance_to_li_target
#check R1961DLeanPacket.no_hidden_residual_boundary_packet_transfer
#check R1961DLeanPacket.finite_to_packet_balance_target
#check R1961DLeanPacket.normalized_finite_tail_boundary_packet_balance_to_li_target
#check R1961DLeanPacket.r1961_critical_slots_are_inherited_from_r1956_interface
#check R1961DLeanPacket.r1961_packet_depth_certificate_records_actual_abstract_theorems
#check R1961DLeanPacket.r1961_packet_layer_keeps_r1958_non_claim_boundary
#check R1961DLeanPacket.toy_packet_balance_runs
#check R1961DLeanPacket.toy_boundary_packet_balance_runs
#check R1961DLeanPacket.toy_finite_tail_packet_balance_runs
#check R1961DLeanPacket.toy_finite_to_packet_balance_witness_runs
#check R1961DLeanPacket.toy_normalized_finite_tail_packet_balance_runs
#check R1961DLeanPacket.r1961_version_declares_packet_balance_layer

#check R1962DLeanAnalyticRealization.inherited_packet_slots_are_r1961_packet_slots
#check R1962DLeanAnalyticRealization.toExplicitPacketBalanceSystem
#check R1962DLeanAnalyticRealization.analytic_realization_packet_balance_to_li_target
#check R1962DLeanAnalyticRealization.r1962_first_step_is_target_language_not_full_analytic_proof
#check R1962DLeanAnalyticRealization.toy_analytic_realization_packet_bridge_runs
#check R1962DLeanAnalyticRealization.toy_converted_packet_system_runs

#check R1963DLeanAnalyticDecomposition.profileOfSlot
#check R1963DLeanAnalyticDecomposition.every_slot_has_profile
#check R1963DLeanAnalyticDecomposition.profile_non_claim_boundary
#check R1963DLeanAnalyticDecomposition.providesCommonAnchor
#check R1963DLeanAnalyticDecomposition.feedsPacketControl
#check R1963DLeanAnalyticDecomposition.slotRealized
#check R1963DLeanAnalyticDecomposition.RealizedAnalyticPreTargetSlots
#check R1963DLeanAnalyticDecomposition.realized_pre_target_slots_to_actual_li_target
#check R1963DLeanAnalyticDecomposition.defaultAnalyticObligationDecompositionMatrix
#check R1963DLeanAnalyticDecomposition.default_matrix_profiles_match_slots
#check R1963DLeanAnalyticDecomposition.default_matrix_kernel_is_anchor
#check R1963DLeanAnalyticDecomposition.default_matrix_prime_feeds_packet
#check R1963DLeanAnalyticDecomposition.r1963_second_step_is_decomposition_not_full_analytic_proof
#check R1963DLeanAnalyticDecomposition.toyRealizedAnalyticPreTargetSlots
#check R1963DLeanAnalyticDecomposition.toy_decomposition_bridge_runs
#check R1963DLeanAnalyticDecomposition.toy_decomposition_agrees_with_r1962_bridge
#check R1963DLeanAnalyticDecomposition.toy_default_matrix_has_profiles
#check R1964DLeanAnalyticMicroTargets.AnalyticMicroTargetSystem
#check R1964DLeanAnalyticMicroTargets.AnalyticMicroTargetWitnesses
#check R1964DLeanAnalyticMicroTargets.micro_targets_to_pre_target_slots
#check R1964DLeanAnalyticMicroTargets.micro_targets_to_actual_li_target
#check R1964DLeanAnalyticMicroTargets.r1964_third_step_is_micro_target_refinement_not_full_analytic_proof
#check R1964DLeanAnalyticMicroTargets.toyAnalyticMicroTargetSystem
#check R1964DLeanAnalyticMicroTargets.toy_micro_targets_produce_pre_target_slots
#check R1964DLeanAnalyticMicroTargets.toy_micro_targets_to_actual_li_target_runs

#check R1965DLeanRealizationInterfaces.ActualAnalyticRealizationInterfaces
#check R1965DLeanRealizationInterfaces.ActualAnalyticRealizationEvidence
#check R1965DLeanRealizationInterfaces.interfacesToMicroTargetSystem
#check R1965DLeanRealizationInterfaces.evidenceToMicroTargetWitnesses
#check R1965DLeanRealizationInterfaces.realized_interfaces_to_pre_target_slots
#check R1965DLeanRealizationInterfaces.realized_interfaces_to_actual_li_target
#check R1965DLeanRealizationInterfaces.r1965_fourth_step_is_realization_interface_not_full_analytic_proof
#check R1965DLeanRealizationInterfaces.toyActualAnalyticRealizationInterfaces
#check R1965DLeanRealizationInterfaces.toy_realization_interfaces_produce_micro_target_system
#check R1965DLeanRealizationInterfaces.toy_realization_interfaces_produce_pre_target_slots
#check R1965DLeanRealizationInterfaces.toy_realization_interfaces_to_actual_li_target_runs


#check R1966DLeanSourceCategories.ConcreteAnalyticSourceKind
#check R1966DLeanSourceCategories.SourceCategoryProfile
#check R1966DLeanSourceCategories.sourceKindOfBlock
#check R1966DLeanSourceCategories.source_profile_non_claim_boundary
#check R1966DLeanSourceCategories.ConcreteAnalyticSourceSystem
#check R1966DLeanSourceCategories.ConcreteAnalyticSourceEvidence
#check R1966DLeanSourceCategories.sourcesToInterfaces
#check R1966DLeanSourceCategories.sourceEvidenceToInterfaceEvidence
#check R1966DLeanSourceCategories.concrete_sources_to_realization_interfaces
#check R1966DLeanSourceCategories.concrete_sources_to_actual_li_target
#check R1966DLeanSourceCategories.r1966_fifth_step_is_source_category_assignment_not_full_analytic_proof
#check R1966DLeanSourceCategories.toyConcreteAnalyticSourceSystem
#check R1966DLeanSourceCategories.toyConcreteAnalyticSourceEvidence
#check R1966DLeanSourceCategories.toy_concrete_sources_to_interfaces_runs
#check R1966DLeanSourceCategories.toy_concrete_sources_to_actual_li_target_runs

#check R1967DLeanSourceEvidence.SourceEvidenceSlotKind
#check R1967DLeanSourceEvidence.SourceEvidenceSlotProfile
#check R1967DLeanSourceEvidence.sourceKindOfEvidenceSlot
#check R1967DLeanSourceEvidence.profileOfEvidenceSlot
#check R1967DLeanSourceEvidence.evidence_slot_profile_non_claim_boundary
#check R1967DLeanSourceEvidence.SourceEvidenceChecklist
#check R1967DLeanSourceEvidence.SourceEvidenceSlotWitnesses
#check R1967DLeanSourceEvidence.slotWitnessesToConcreteSourceEvidence
#check R1967DLeanSourceEvidence.source_evidence_slots_to_realization_interfaces
#check R1967DLeanSourceEvidence.source_evidence_slots_to_pre_target_slots
#check R1967DLeanSourceEvidence.source_evidence_slots_to_actual_li_target
#check R1967DLeanSourceEvidence.r1967_sixth_step_is_source_evidence_checklist_not_full_analytic_proof
#check R1967DLeanSourceEvidence.toySourceEvidenceChecklist
#check R1967DLeanSourceEvidence.toySourceEvidenceSlotWitnesses
#check R1967DLeanSourceEvidence.toy_source_evidence_slots_to_concrete_source_evidence_runs
#check R1967DLeanSourceEvidence.toy_source_evidence_slots_to_interfaces_runs
#check R1967DLeanSourceEvidence.toy_source_evidence_slots_to_pre_target_slots_runs
#check R1967DLeanSourceEvidence.toy_source_evidence_slots_to_actual_li_target_runs

#check R1968DLeanAnchorClassification.EvidenceAnchorKind
#check R1968DLeanAnchorClassification.AnchoredEvidenceSlotProfile
#check R1968DLeanAnchorClassification.anchorKindOfEvidenceSlot
#check R1968DLeanAnchorClassification.profileOfAnchoredEvidenceSlot
#check R1968DLeanAnchorClassification.anchored_profile_records_slot
#check R1968DLeanAnchorClassification.anchored_profile_records_anchor_kind
#check R1968DLeanAnchorClassification.explicit_formula_identity_anchor_kind
#check R1968DLeanAnchorClassification.prime_packet_estimate_anchor_kind
#check R1968DLeanAnchorClassification.AnchoredSourceEvidenceChecklist
#check R1968DLeanAnchorClassification.anchoredChecklistToSourceEvidenceChecklist
#check R1968DLeanAnchorClassification.anchor_classification_to_concrete_source_evidence
#check R1968DLeanAnchorClassification.anchor_classification_to_realization_interfaces
#check R1968DLeanAnchorClassification.anchor_classification_to_pre_target_slots
#check R1968DLeanAnchorClassification.anchor_classification_to_actual_li_target
#check R1968DLeanAnchorClassification.r1968_seventh_step_is_anchor_classification_not_full_analytic_proof
#check R1968DLeanAnchorClassification.toyAnchoredSourceEvidenceChecklist
#check R1968DLeanAnchorClassification.toy_anchor_classification_to_source_evidence_checklist_runs
#check R1968DLeanAnchorClassification.toy_anchor_classification_to_concrete_source_evidence_runs
#check R1968DLeanAnchorClassification.toy_anchor_classification_to_realization_interfaces_runs
#check R1968DLeanAnchorClassification.toy_anchor_classification_to_pre_target_slots_runs
#check R1968DLeanAnchorClassification.toy_anchor_classification_to_actual_li_target_runs

#check R1969DLeanFormalizationPriority.FormalizationPriority
#check R1969DLeanFormalizationPriority.DependencySeverity
#check R1969DLeanFormalizationPriority.RemainingProofBurden
#check R1969DLeanFormalizationPriority.priorityOfAnchorKind
#check R1969DLeanFormalizationPriority.severityOfAnchorKind
#check R1969DLeanFormalizationPriority.burdenOfAnchorKind
#check R1969DLeanFormalizationPriority.priorityOfEvidenceSlot
#check R1969DLeanFormalizationPriority.severityOfEvidenceSlot
#check R1969DLeanFormalizationPriority.burdenOfEvidenceSlot
#check R1969DLeanFormalizationPriority.PrioritizedAnchorProfile
#check R1969DLeanFormalizationPriority.prioritizedProfileOfEvidenceSlot
#check R1969DLeanFormalizationPriority.prioritized_profile_records_slot
#check R1969DLeanFormalizationPriority.prioritized_profile_records_anchor_kind
#check R1969DLeanFormalizationPriority.prioritized_profile_records_priority
#check R1969DLeanFormalizationPriority.prioritized_profile_records_severity
#check R1969DLeanFormalizationPriority.prioritized_profile_non_claim_boundary
#check R1969DLeanFormalizationPriority.new_analytic_anchor_is_immediate_core
#check R1969DLeanFormalizationPriority.external_classical_anchor_is_high_priority
#check R1969DLeanFormalizationPriority.audit_anchor_is_ledger_only_priority
#check R1969DLeanFormalizationPriority.prime_packet_estimate_priority_is_immediate_core
#check R1969DLeanFormalizationPriority.explicit_formula_identity_priority_is_high
#check R1969DLeanFormalizationPriority.FormalizationPriorityPlan
#check R1969DLeanFormalizationPriority.priorityPlanToAnchoredChecklist
#check R1969DLeanFormalizationPriority.priorityPlanToSourceEvidenceChecklist
#check R1969DLeanFormalizationPriority.priority_plan_to_realization_interfaces
#check R1969DLeanFormalizationPriority.priority_plan_to_pre_target_slots
#check R1969DLeanFormalizationPriority.priority_plan_to_actual_li_target
#check R1969DLeanFormalizationPriority.r1969_eighth_step_is_priority_ordering_not_full_analytic_proof
#check R1969DLeanFormalizationPriority.toyFormalizationPriorityPlan
#check R1969DLeanFormalizationPriority.toy_priority_plan_to_anchored_checklist_runs
#check R1969DLeanFormalizationPriority.toy_priority_plan_to_realization_interfaces_runs
#check R1969DLeanFormalizationPriority.toy_priority_plan_to_pre_target_slots_runs
#check R1969DLeanFormalizationPriority.toy_priority_plan_to_actual_li_target_runs
#check R1969DLeanFormalizationPriority.toy_prime_packet_estimate_is_immediate_core


#check R1970DLeanFirstFormalizationTarget.FirstFormalizationTargetKind
#check R1970DLeanFirstFormalizationTarget.evidenceSlotOfFirstTarget
#check R1970DLeanFirstFormalizationTarget.sourceKindOfFirstTarget
#check R1970DLeanFirstFormalizationTarget.anchorKindOfFirstTarget
#check R1970DLeanFirstFormalizationTarget.priorityOfFirstTarget
#check R1970DLeanFirstFormalizationTarget.severityOfFirstTarget
#check R1970DLeanFirstFormalizationTarget.burdenOfFirstTarget
#check R1970DLeanFirstFormalizationTarget.recommendedFirstFormalizationTarget
#check R1970DLeanFirstFormalizationTarget.FirstFormalizationTargetProfile
#check R1970DLeanFirstFormalizationTarget.profileOfFirstTargetKind
#check R1970DLeanFirstFormalizationTarget.first_target_profile_records_target
#check R1970DLeanFirstFormalizationTarget.first_target_profile_records_evidence_slot
#check R1970DLeanFirstFormalizationTarget.first_target_profile_records_source_kind
#check R1970DLeanFirstFormalizationTarget.first_target_profile_non_claim_boundary
#check R1970DLeanFirstFormalizationTarget.recommended_first_target_is_abel_boundary_definition
#check R1970DLeanFirstFormalizationTarget.recommended_first_target_evidence_slot
#check R1970DLeanFirstFormalizationTarget.recommended_first_target_anchor_kind
#check R1970DLeanFirstFormalizationTarget.recommended_first_target_priority
#check R1970DLeanFirstFormalizationTarget.MinimalFirstFormalizationPlan
#check R1970DLeanFirstFormalizationTarget.minimalFirstTargetPlanToPriorityPlan
#check R1970DLeanFirstFormalizationTarget.minimal_first_target_plan_to_anchored_checklist
#check R1970DLeanFirstFormalizationTarget.minimal_first_target_plan_to_source_evidence_checklist
#check R1970DLeanFirstFormalizationTarget.minimal_first_target_plan_to_realization_interfaces
#check R1970DLeanFirstFormalizationTarget.minimal_first_target_plan_to_pre_target_slots
#check R1970DLeanFirstFormalizationTarget.minimal_first_target_plan_to_actual_li_target
#check R1970DLeanFirstFormalizationTarget.r1970_ninth_step_is_first_target_selection_not_full_analytic_proof
#check R1970DLeanFirstFormalizationTarget.toyMinimalFirstFormalizationPlan
#check R1970DLeanFirstFormalizationTarget.toy_minimal_first_target_to_priority_plan_runs
#check R1970DLeanFirstFormalizationTarget.toy_minimal_first_target_to_anchored_checklist_runs
#check R1970DLeanFirstFormalizationTarget.toy_minimal_first_target_to_source_evidence_checklist_runs
#check R1970DLeanFirstFormalizationTarget.toy_minimal_first_target_to_realization_interfaces_runs
#check R1970DLeanFirstFormalizationTarget.toy_minimal_first_target_to_pre_target_slots_runs
#check R1970DLeanFirstFormalizationTarget.toy_minimal_first_target_to_actual_li_target_runs
#check R1970DLeanFirstFormalizationTarget.toy_selected_first_target_is_recommended


#check R1971DLeanAbelBoundarySkeleton.AbelBoundaryParameterList
#check R1971DLeanAbelBoundarySkeleton.AbelBoundaryAdmissibilityHypotheses
#check R1971DLeanAbelBoundarySkeleton.AbelBoundaryDefinitionSkeleton
#check R1971DLeanAbelBoundarySkeleton.AbelBoundaryTargetStatementShell
#check R1971DLeanAbelBoundarySkeleton.abelBoundarySkeletonFirstTarget
#check R1971DLeanAbelBoundarySkeleton.abel_boundary_skeleton_target_is_recommended
#check R1971DLeanAbelBoundarySkeleton.abel_boundary_skeleton_target_evidence_slot
#check R1971DLeanAbelBoundarySkeleton.abel_boundary_skeleton_target_anchor_kind
#check R1971DLeanAbelBoundarySkeleton.abel_boundary_skeleton_target_priority
#check R1971DLeanAbelBoundarySkeleton.parameter_list_non_claim_boundary
#check R1971DLeanAbelBoundarySkeleton.statement_shell_records_no_abel_boundary_proof
#check R1971DLeanAbelBoundarySkeleton.AbelBoundaryDefinitionSkeletonPlan
#check R1971DLeanAbelBoundarySkeleton.abelBoundarySkeletonPlanToMinimalFirstTargetPlan
#check R1971DLeanAbelBoundarySkeleton.abel_boundary_skeleton_to_priority_plan
#check R1971DLeanAbelBoundarySkeleton.abel_boundary_skeleton_to_anchored_checklist
#check R1971DLeanAbelBoundarySkeleton.abel_boundary_skeleton_to_source_evidence_checklist
#check R1971DLeanAbelBoundarySkeleton.abel_boundary_skeleton_to_realization_interfaces
#check R1971DLeanAbelBoundarySkeleton.abel_boundary_skeleton_to_pre_target_slots
#check R1971DLeanAbelBoundarySkeleton.abel_boundary_skeleton_to_actual_li_target
#check R1971DLeanAbelBoundarySkeleton.r1971_tenth_step_is_definition_skeleton_not_abel_boundary_proof
#check R1971DLeanAbelBoundarySkeleton.toyAbelBoundaryParameterList
#check R1971DLeanAbelBoundarySkeleton.toyAbelBoundaryAdmissibilityHypotheses
#check R1971DLeanAbelBoundarySkeleton.toyAbelBoundaryDefinitionSkeleton
#check R1971DLeanAbelBoundarySkeleton.toyAbelBoundaryTargetStatementShell
#check R1971DLeanAbelBoundarySkeleton.toyAbelBoundaryDefinitionSkeletonPlan
#check R1971DLeanAbelBoundarySkeleton.toy_abel_boundary_skeleton_to_minimal_plan_runs
#check R1971DLeanAbelBoundarySkeleton.toy_abel_boundary_skeleton_to_priority_plan_runs
#check R1971DLeanAbelBoundarySkeleton.toy_abel_boundary_skeleton_to_realization_interfaces_runs
#check R1971DLeanAbelBoundarySkeleton.toy_abel_boundary_skeleton_to_pre_target_slots_runs
#check R1971DLeanAbelBoundarySkeleton.toy_abel_boundary_skeleton_to_actual_li_target_runs
#check R1971DLeanAbelBoundarySkeleton.toy_abel_boundary_skeleton_target_is_abel_definition
#check R1971DLeanAbelBoundarySkeleton.toy_statement_shell_does_not_prove_abel_identity


#check R1972DLeanToyAbelModel.FiniteSurrogateAbelTransform
#check R1972DLeanToyAbelModel.BoundaryLimitPlaceholder
#check R1972DLeanToyAbelModel.ToyAnalyticAbelModel
#check R1972DLeanToyAbelModel.toy_abel_model_target_is_abel_boundary_definition
#check R1972DLeanToyAbelModel.finite_surrogate_uses_r1971_skeleton
#check R1972DLeanToyAbelModel.boundary_placeholder_records_no_actual_limit_proof
#check R1972DLeanToyAbelModel.boundary_placeholder_records_no_abel_boundary_identity_proof
#check R1972DLeanToyAbelModel.ToyAnalyticAbelModelPlan
#check R1972DLeanToyAbelModel.toyAbelModelPlanToSkeletonPlan
#check R1972DLeanToyAbelModel.toy_abel_model_to_minimal_first_target_plan
#check R1972DLeanToyAbelModel.toy_abel_model_to_priority_plan
#check R1972DLeanToyAbelModel.toy_abel_model_to_anchored_checklist
#check R1972DLeanToyAbelModel.toy_abel_model_to_source_evidence_checklist
#check R1972DLeanToyAbelModel.toy_abel_model_to_realization_interfaces
#check R1972DLeanToyAbelModel.toy_abel_model_to_pre_target_slots
#check R1972DLeanToyAbelModel.toy_abel_model_to_actual_li_target
#check R1972DLeanToyAbelModel.r1972_eleventh_step_is_toy_model_not_concrete_abel_boundary_proof
#check R1972DLeanToyAbelModel.toyFiniteSurrogateAbelTransform
#check R1972DLeanToyAbelModel.toyBoundaryLimitPlaceholder
#check R1972DLeanToyAbelModel.toyAnalyticAbelModel
#check R1972DLeanToyAbelModel.toyAnalyticAbelModelPlan
#check R1972DLeanToyAbelModel.toy_abel_model_to_skeleton_plan_runs
#check R1972DLeanToyAbelModel.toy_abel_model_to_minimal_first_target_plan_runs
#check R1972DLeanToyAbelModel.toy_abel_model_to_priority_plan_runs
#check R1972DLeanToyAbelModel.toy_abel_model_to_realization_interfaces_runs
#check R1972DLeanToyAbelModel.toy_abel_model_to_pre_target_slots_runs
#check R1972DLeanToyAbelModel.toy_abel_model_to_actual_li_target_runs
#check R1972DLeanToyAbelModel.toy_finite_surrogate_uses_skeleton
#check R1972DLeanToyAbelModel.toy_boundary_limit_placeholder_does_not_prove_limit
#check R1972DLeanToyAbelModel.toy_boundary_limit_placeholder_does_not_prove_identity
#check R1972DLeanToyAbelModel.toy_abel_model_target_is_abel_definition

#check R1973DLeanFiniteAbelIdentity.FiniteAbelTransformIdentityShell
#check R1973DLeanFiniteAbelIdentity.BoundaryCompatibilityLemmaShell
#check R1973DLeanFiniteAbelIdentity.FiniteAbelIdentityShellPlan
#check R1973DLeanFiniteAbelIdentity.finite_identity_shell_to_toy_abel_model_plan
#check R1973DLeanFiniteAbelIdentity.finite_identity_shell_to_skeleton_plan
#check R1973DLeanFiniteAbelIdentity.finite_identity_shell_to_minimal_first_target_plan
#check R1973DLeanFiniteAbelIdentity.finite_identity_shell_to_pre_target_slots
#check R1973DLeanFiniteAbelIdentity.finite_identity_shell_target_is_abel_boundary_definition
#check R1973DLeanFiniteAbelIdentity.finite_abel_identity_to_toy_abel_model_plan
#check R1973DLeanFiniteAbelIdentity.finite_abel_identity_to_abel_boundary_skeleton
#check R1973DLeanFiniteAbelIdentity.finite_abel_identity_to_minimal_first_target_plan
#check R1973DLeanFiniteAbelIdentity.finite_abel_identity_to_priority_plan
#check R1973DLeanFiniteAbelIdentity.finite_abel_identity_to_realization_interfaces
#check R1973DLeanFiniteAbelIdentity.finite_abel_identity_to_pre_target_slots
#check R1973DLeanFiniteAbelIdentity.finite_abel_identity_shell_to_actual_li_target
#check R1973DLeanFiniteAbelIdentity.r1973_twelfth_step_is_identity_shell_not_concrete_abel_boundary_proof
#check R1973DLeanFiniteAbelIdentity.toyFiniteAbelTransformIdentityShell
#check R1973DLeanFiniteAbelIdentity.toyBoundaryCompatibilityLemmaShell
#check R1973DLeanFiniteAbelIdentity.toyFiniteAbelIdentityShellPlan
#check R1973DLeanFiniteAbelIdentity.toy_finite_identity_to_toy_abel_model_plan_runs
#check R1973DLeanFiniteAbelIdentity.toy_finite_identity_to_skeleton_plan_runs
#check R1973DLeanFiniteAbelIdentity.toy_finite_identity_to_minimal_first_target_plan_runs
#check R1973DLeanFiniteAbelIdentity.toy_finite_identity_to_priority_plan_runs
#check R1973DLeanFiniteAbelIdentity.toy_finite_identity_to_realization_interfaces_runs
#check R1973DLeanFiniteAbelIdentity.toy_finite_identity_to_pre_target_slots_runs
#check R1973DLeanFiniteAbelIdentity.toy_finite_abel_identity_shell_to_actual_li_target_runs
#check R1973DLeanFiniteAbelIdentity.toy_finite_identity_statement_shell_registered
#check R1973DLeanFiniteAbelIdentity.toy_finite_identity_shell_does_not_prove_concrete_identity
#check R1973DLeanFiniteAbelIdentity.toy_boundary_compatibility_shell_does_not_prove_boundary_limit
#check R1973DLeanFiniteAbelIdentity.toy_finite_identity_target_is_abel_definition


#check R1974DLeanFiniteAbelComponents.FiniteSumOperatorSlot
#check R1974DLeanFiniteAbelComponents.FiniteAbelWeightSystemSlot
#check R1974DLeanFiniteAbelComponents.EndpointCorrectionSlot
#check R1974DLeanFiniteAbelComponents.BoundaryErrorTermSlot
#check R1974DLeanFiniteAbelComponents.FiniteAbelComponentPlan
#check R1974DLeanFiniteAbelComponents.components_to_finite_identity_shell_plan
#check R1974DLeanFiniteAbelComponents.components_to_toy_abel_model_plan
#check R1974DLeanFiniteAbelComponents.components_to_abel_boundary_skeleton_plan
#check R1974DLeanFiniteAbelComponents.components_to_minimal_first_target_plan
#check R1974DLeanFiniteAbelComponents.components_to_pre_target_slots
#check R1974DLeanFiniteAbelComponents.finite_abel_components_to_identity_shell_plan
#check R1974DLeanFiniteAbelComponents.finite_abel_components_to_toy_abel_model_plan
#check R1974DLeanFiniteAbelComponents.finite_abel_components_to_abel_boundary_skeleton
#check R1974DLeanFiniteAbelComponents.finite_abel_components_to_minimal_first_target_plan
#check R1974DLeanFiniteAbelComponents.finite_abel_components_to_priority_plan
#check R1974DLeanFiniteAbelComponents.finite_abel_components_to_realization_interfaces
#check R1974DLeanFiniteAbelComponents.finite_abel_components_to_pre_target_slots
#check R1974DLeanFiniteAbelComponents.finite_abel_components_to_actual_li_target
#check R1974DLeanFiniteAbelComponents.r1974_thirteenth_step_is_component_shell_not_concrete_abel_proof
#check R1974DLeanFiniteAbelComponents.toyFiniteSumOperatorSlot
#check R1974DLeanFiniteAbelComponents.toyFiniteAbelWeightSystemSlot
#check R1974DLeanFiniteAbelComponents.toyEndpointCorrectionSlot
#check R1974DLeanFiniteAbelComponents.toyBoundaryErrorTermSlot
#check R1974DLeanFiniteAbelComponents.toyFiniteAbelComponentPlan
#check R1974DLeanFiniteAbelComponents.toy_components_to_finite_identity_shell_plan_runs
#check R1974DLeanFiniteAbelComponents.toy_components_to_toy_abel_model_plan_runs
#check R1974DLeanFiniteAbelComponents.toy_components_to_skeleton_plan_runs
#check R1974DLeanFiniteAbelComponents.toy_components_to_minimal_first_target_plan_runs
#check R1974DLeanFiniteAbelComponents.toy_components_to_priority_plan_runs
#check R1974DLeanFiniteAbelComponents.toy_components_to_realization_interfaces_runs
#check R1974DLeanFiniteAbelComponents.toy_components_to_pre_target_slots_runs
#check R1974DLeanFiniteAbelComponents.toy_finite_abel_components_to_actual_li_target_runs
#check R1974DLeanFiniteAbelComponents.toy_finite_sum_operator_does_not_prove_concrete_summation
#check R1974DLeanFiniteAbelComponents.toy_endpoint_correction_does_not_prove_endpoint_estimate
#check R1974DLeanFiniteAbelComponents.toy_boundary_error_term_does_not_prove_boundary_limit
#check R1974DLeanFiniteAbelComponents.toy_finite_components_target_is_abel_definition

/-!
R1983D continuation checks.
These checks restore the long R1974D main-manuscript verification spine above
and attach the R1975D--R1983D continuation layers to it.
-/

#check R1980DLeanConcreteEstimateStatements.concrete_estimate_statement_bank_to_actual_li_target
#check R1980DLeanConcreteEstimateStatements.statement_bank_to_blueprint_plan
#check R1980DLeanConcreteEstimateStatements.r1980_nineteenth_step_is_statement_bank_not_estimate_proof
#check R1982DLeanProofObligationExecutionPlan.concrete_proof_obligation_execution_plan_to_actual_li_target
#check R1982DLeanProofObligationExecutionPlan.execution_plan_to_statement_bank
#check R1982DLeanProofObligationExecutionPlan.execution_order_to_plan
#check R1982DLeanProofObligationExecutionPlan.r1982_twenty_first_step_is_execution_plan_not_concrete_estimate_proof
#check R1982DLeanProofObligationExecutionPlan.r1982_twenty_first_step_does_not_claim_rh_formalization
#check R1983DLeanMainManuscriptAnchoredVerificationSpine.MainManuscriptAnchorSpine
#check R1983DLeanMainManuscriptAnchoredVerificationSpine.MainManuscriptAnchoredVerificationLedger
#check R1983DLeanMainManuscriptAnchoredVerificationSpine.main_manuscript_anchor_spine_to_execution_plan
#check R1983DLeanMainManuscriptAnchoredVerificationSpine.main_manuscript_anchor_spine_to_statement_bank
#check R1983DLeanMainManuscriptAnchoredVerificationSpine.main_manuscript_anchored_verification_spine_to_actual_li_target
#check R1983DLeanMainManuscriptAnchoredVerificationSpine.r1983_twenty_second_step_is_main_manuscript_anchor_not_concrete_estimate_proof
#check R1983DLeanMainManuscriptAnchoredVerificationSpine.r1983_twenty_second_step_preserves_historical_main_lean_check_spine
#check R1983DLeanMainManuscriptAnchoredVerificationSpine.r1983_twenty_second_step_preserves_r1975_to_r1982_continuation_layers
#check R1983DLeanMainManuscriptAnchoredVerificationSpine.r1983_twenty_second_step_does_not_claim_rh_formalization
#check R1983DLeanMainManuscriptAnchoredVerificationSpine.toy_main_manuscript_anchor_spine_to_execution_plan_runs
#check R1983DLeanMainManuscriptAnchoredVerificationSpine.toy_main_manuscript_anchored_spine_to_actual_li_target_runs


/-!
R1984D continuation checks.
These checks attach the first implementation queue to the R1983D
main-manuscript-anchored verification spine without narrowing the historical
aggregate build graph.
-/

#check R1984DLeanManuscriptObligationImplementationQueue.MainAnchoredObligationFamily
#check R1984DLeanManuscriptObligationImplementationQueue.MainAnchoredQueueStage
#check R1984DLeanManuscriptObligationImplementationQueue.MainAnchoredImplementationQueueEntry
#check R1984DLeanManuscriptObligationImplementationQueue.MainAnchoredFirstObligationImplementationQueue
#check R1984DLeanManuscriptObligationImplementationQueue.MainAnchoredFirstImplementationFrontier
#check R1984DLeanManuscriptObligationImplementationQueue.main_anchored_queue_to_anchor_spine
#check R1984DLeanManuscriptObligationImplementationQueue.main_anchored_queue_to_execution_plan
#check R1984DLeanManuscriptObligationImplementationQueue.main_anchored_queue_to_statement_bank
#check R1984DLeanManuscriptObligationImplementationQueue.manuscript_obligation_queue_to_anchor_spine
#check R1984DLeanManuscriptObligationImplementationQueue.manuscript_obligation_queue_to_execution_plan
#check R1984DLeanManuscriptObligationImplementationQueue.manuscript_obligation_queue_to_statement_bank
#check R1984DLeanManuscriptObligationImplementationQueue.manuscript_anchored_obligation_queue_to_actual_li_target
#check R1984DLeanManuscriptObligationImplementationQueue.r1984_twenty_third_step_is_queue_not_endpoint_estimate_proof
#check R1984DLeanManuscriptObligationImplementationQueue.r1984_twenty_third_step_preserves_r1983_anchor_bridge
#check R1984DLeanManuscriptObligationImplementationQueue.r1984_twenty_third_step_records_first_dependency_frontier
#check R1984DLeanManuscriptObligationImplementationQueue.r1984_twenty_third_step_does_not_claim_rh_formalization
#check R1984DLeanManuscriptObligationImplementationQueue.toy_manuscript_obligation_queue_to_anchor_spine_runs
#check R1984DLeanManuscriptObligationImplementationQueue.toy_manuscript_obligation_queue_to_execution_plan_runs
#check R1984DLeanManuscriptObligationImplementationQueue.toy_manuscript_anchored_obligation_queue_to_actual_li_target_runs
#check R1984DLeanManuscriptObligationImplementationQueue.toy_first_implementation_frontier_to_queue_runs


/-!
R1985D continuation checks.
These checks isolate the endpoint family as the first manuscript-anchored
implementation block while preserving the R1984D queue and the R1983D
main-manuscript verification spine.
-/

#check R1985DLeanEndpointFirstImplementationBlock.EndpointFirstImplementationStage
#check R1985DLeanEndpointFirstImplementationBlock.EndpointLocalReductionTag
#check R1985DLeanEndpointFirstImplementationBlock.MainAnchoredEndpointFirstImplementationBlock
#check R1985DLeanEndpointFirstImplementationBlock.EndpointFirstBlockDependencyKind
#check R1985DLeanEndpointFirstImplementationBlock.EndpointFirstBlockDependencyItem
#check R1985DLeanEndpointFirstImplementationBlock.EndpointFirstBlockDependencyFrontier
#check R1985DLeanEndpointFirstImplementationBlock.endpoint_first_block_to_queue
#check R1985DLeanEndpointFirstImplementationBlock.endpoint_first_block_to_anchor_spine
#check R1985DLeanEndpointFirstImplementationBlock.endpoint_first_block_to_execution_plan
#check R1985DLeanEndpointFirstImplementationBlock.endpoint_first_block_to_statement_bank
#check R1985DLeanEndpointFirstImplementationBlock.endpoint_implementation_block_to_queue
#check R1985DLeanEndpointFirstImplementationBlock.endpoint_implementation_block_to_anchor_spine
#check R1985DLeanEndpointFirstImplementationBlock.endpoint_first_implementation_block_to_actual_li_target
#check R1985DLeanEndpointFirstImplementationBlock.r1985_twenty_fourth_step_selects_endpoint_family_first
#check R1985DLeanEndpointFirstImplementationBlock.r1985_twenty_fourth_step_records_endpoint_dependency_frontier
#check R1985DLeanEndpointFirstImplementationBlock.r1985_twenty_fourth_step_is_endpoint_block_not_endpoint_estimate_proof
#check R1985DLeanEndpointFirstImplementationBlock.r1985_twenty_fourth_step_does_not_claim_rh_formalization
#check R1985DLeanEndpointFirstImplementationBlock.toy_endpoint_first_block_to_queue_runs
#check R1985DLeanEndpointFirstImplementationBlock.toy_endpoint_first_block_to_anchor_spine_runs
#check R1985DLeanEndpointFirstImplementationBlock.toy_endpoint_first_implementation_block_to_actual_li_target_runs
#check R1985DLeanEndpointFirstImplementationBlock.toy_endpoint_dependency_frontier_to_block_runs


/-!
R1986D continuation checks.
These checks refine the R1985D endpoint implementation block into the first
endpoint statement group and its ordered dependency spine, without closing the
endpoint estimate or any RH-level claim.
-/

#check R1986DLeanEndpointStatementGroup.EndpointStatementGroupStage
#check R1986DLeanEndpointStatementGroup.EndpointStatementGroupKind
#check R1986DLeanEndpointStatementGroup.MainAnchoredEndpointStatementGroup
#check R1986DLeanEndpointStatementGroup.EndpointStatementDependencyOrderKind
#check R1986DLeanEndpointStatementGroup.EndpointStatementDependencyStep
#check R1986DLeanEndpointStatementGroup.EndpointStatementGroupDependencyOrder
#check R1986DLeanEndpointStatementGroup.endpoint_statement_group_to_block
#check R1986DLeanEndpointStatementGroup.endpoint_statement_group_to_queue
#check R1986DLeanEndpointStatementGroup.endpoint_statement_group_to_anchor_spine
#check R1986DLeanEndpointStatementGroup.endpoint_statement_group_to_statement_bank
#check R1986DLeanEndpointStatementGroup.endpoint_statement_group_to_endpoint_block
#check R1986DLeanEndpointStatementGroup.endpoint_statement_group_to_endpoint_queue
#check R1986DLeanEndpointStatementGroup.endpoint_statement_dependency_order_to_group
#check R1986DLeanEndpointStatementGroup.endpoint_statement_group_to_actual_li_target
#check R1986DLeanEndpointStatementGroup.r1986_twenty_fifth_step_records_endpoint_statement_group
#check R1986DLeanEndpointStatementGroup.r1986_twenty_fifth_step_records_endpoint_statement_dependency_order
#check R1986DLeanEndpointStatementGroup.r1986_twenty_fifth_step_is_statement_group_not_endpoint_estimate_proof
#check R1986DLeanEndpointStatementGroup.r1986_twenty_fifth_step_does_not_claim_rh_formalization
#check R1986DLeanEndpointStatementGroup.toy_endpoint_statement_group_to_block_runs
#check R1986DLeanEndpointStatementGroup.toy_endpoint_statement_group_to_queue_runs
#check R1986DLeanEndpointStatementGroup.toy_endpoint_statement_group_to_actual_li_target_runs
#check R1986DLeanEndpointStatementGroup.toy_endpoint_statement_dependency_order_to_group_runs


/-!
R1987D continuation checks.
These checks refine the R1986D endpoint statement group into the first
endpoint proof-kernel interface.  The layer records proof-kernel carriers and
dependency interfaces only; it does not close the endpoint estimate or any
RH-level claim.
-/

#check R1987DLeanEndpointProofKernelInterface.EndpointProofKernelInterfaceStage
#check R1987DLeanEndpointProofKernelInterface.EndpointProofKernelRouteKind
#check R1987DLeanEndpointProofKernelInterface.MainAnchoredEndpointProofKernelInterface
#check R1987DLeanEndpointProofKernelInterface.EndpointProofKernelDependencyKind
#check R1987DLeanEndpointProofKernelInterface.EndpointProofKernelDependencyItem
#check R1987DLeanEndpointProofKernelInterface.EndpointProofKernelDependencyInterface
#check R1987DLeanEndpointProofKernelInterface.endpoint_proof_kernel_interface_to_statement_group
#check R1987DLeanEndpointProofKernelInterface.endpoint_proof_kernel_interface_to_endpoint_block
#check R1987DLeanEndpointProofKernelInterface.endpoint_proof_kernel_interface_to_queue
#check R1987DLeanEndpointProofKernelInterface.endpoint_proof_kernel_interface_to_anchor_spine
#check R1987DLeanEndpointProofKernelInterface.endpoint_proof_kernel_interface_to_statement_bank
#check R1987DLeanEndpointProofKernelInterface.endpoint_proof_kernel_to_endpoint_statement_group
#check R1987DLeanEndpointProofKernelInterface.endpoint_proof_kernel_to_endpoint_queue
#check R1987DLeanEndpointProofKernelInterface.endpoint_proof_kernel_dependency_interface_to_kernel
#check R1987DLeanEndpointProofKernelInterface.endpoint_proof_kernel_interface_to_actual_li_target
#check R1987DLeanEndpointProofKernelInterface.r1987_twenty_sixth_step_records_endpoint_proof_kernel_interface
#check R1987DLeanEndpointProofKernelInterface.r1987_twenty_sixth_step_records_endpoint_kernel_dependency_interface
#check R1987DLeanEndpointProofKernelInterface.r1987_twenty_sixth_step_is_kernel_interface_not_endpoint_estimate_proof
#check R1987DLeanEndpointProofKernelInterface.r1987_twenty_sixth_step_does_not_claim_rh_formalization
#check R1987DLeanEndpointProofKernelInterface.toy_endpoint_proof_kernel_interface_to_statement_group_runs
#check R1987DLeanEndpointProofKernelInterface.toy_endpoint_proof_kernel_interface_to_queue_runs
#check R1987DLeanEndpointProofKernelInterface.toy_endpoint_proof_kernel_interface_to_actual_li_target_runs
#check R1987DLeanEndpointProofKernelInterface.toy_endpoint_kernel_dependency_interface_to_kernel_runs


/-!
R1988D continuation checks.
These checks refine the R1987D endpoint proof-kernel interface into an endpoint
kernel axiom boundary and first concrete lemma boundary.  The layer records the
boundary at which later endpoint proof files must begin; it does not discharge
an endpoint estimate or any RH-level claim.
-/

#check R1988DLeanEndpointKernelAxiomBoundary.EndpointKernelAxiomBoundaryStage
#check R1988DLeanEndpointKernelAxiomBoundary.EndpointKernelAxiomBoundaryKind
#check R1988DLeanEndpointKernelAxiomBoundary.MainAnchoredEndpointKernelAxiomBoundary
#check R1988DLeanEndpointKernelAxiomBoundary.EndpointConcreteLemmaBoundaryKind
#check R1988DLeanEndpointKernelAxiomBoundary.EndpointConcreteLemmaBoundaryItem
#check R1988DLeanEndpointKernelAxiomBoundary.EndpointFirstConcreteLemmaBoundary
#check R1988DLeanEndpointKernelAxiomBoundary.endpoint_kernel_axiom_boundary_to_kernel
#check R1988DLeanEndpointKernelAxiomBoundary.endpoint_kernel_axiom_boundary_to_statement_group
#check R1988DLeanEndpointKernelAxiomBoundary.endpoint_kernel_axiom_boundary_to_queue
#check R1988DLeanEndpointKernelAxiomBoundary.endpoint_kernel_axiom_boundary_to_statement_bank
#check R1988DLeanEndpointKernelAxiomBoundary.endpoint_kernel_axiom_boundary_records_no_endpoint_proof_here
#check R1988DLeanEndpointKernelAxiomBoundary.endpoint_concrete_lemma_boundary_to_axiom_boundary
#check R1988DLeanEndpointKernelAxiomBoundary.endpoint_concrete_lemma_boundary_records_no_endpoint_proof_here
#check R1988DLeanEndpointKernelAxiomBoundary.endpoint_kernel_axiom_boundary_to_actual_li_target
#check R1988DLeanEndpointKernelAxiomBoundary.r1988_twenty_seventh_step_records_endpoint_kernel_axiom_boundary
#check R1988DLeanEndpointKernelAxiomBoundary.r1988_twenty_seventh_step_records_first_concrete_lemma_boundary
#check R1988DLeanEndpointKernelAxiomBoundary.r1988_twenty_seventh_step_is_axiom_boundary_not_endpoint_estimate_proof
#check R1988DLeanEndpointKernelAxiomBoundary.r1988_twenty_seventh_step_does_not_claim_rh_formalization
#check R1988DLeanEndpointKernelAxiomBoundary.toy_endpoint_kernel_axiom_boundary_to_kernel_runs
#check R1988DLeanEndpointKernelAxiomBoundary.toy_endpoint_kernel_axiom_boundary_to_queue_runs
#check R1988DLeanEndpointKernelAxiomBoundary.toy_endpoint_kernel_axiom_boundary_to_actual_li_target_runs
#check R1988DLeanEndpointKernelAxiomBoundary.toy_endpoint_concrete_lemma_boundary_to_axiom_boundary_runs


/-!
R1989D continuation checks.
These checks refine the R1988D endpoint kernel axiom boundary and first concrete
lemma boundary into a concrete-lemma stub bank and dependency grid.  The layer
records the first proof-file stubs only; it does not discharge an endpoint
estimate or any RH-level claim.
-/

#check R1989DLeanEndpointConcreteLemmaStubs.EndpointConcreteLemmaStubStage
#check R1989DLeanEndpointConcreteLemmaStubs.EndpointConcreteLemmaStubKind
#check R1989DLeanEndpointConcreteLemmaStubs.EndpointConcreteLemmaStubItem
#check R1989DLeanEndpointConcreteLemmaStubs.MainAnchoredEndpointConcreteLemmaStubBank
#check R1989DLeanEndpointConcreteLemmaStubs.EndpointLemmaStubDependencyKind
#check R1989DLeanEndpointConcreteLemmaStubs.EndpointLemmaStubDependencyItem
#check R1989DLeanEndpointConcreteLemmaStubs.EndpointLemmaStubDependencyGrid
#check R1989DLeanEndpointConcreteLemmaStubs.endpoint_concrete_lemma_stub_bank_to_first_boundary
#check R1989DLeanEndpointConcreteLemmaStubs.endpoint_concrete_lemma_stub_bank_to_axiom_boundary
#check R1989DLeanEndpointConcreteLemmaStubs.endpoint_concrete_lemma_stub_bank_to_kernel
#check R1989DLeanEndpointConcreteLemmaStubs.endpoint_concrete_lemma_stub_bank_to_statement_bank
#check R1989DLeanEndpointConcreteLemmaStubs.endpoint_concrete_lemma_stub_bank_records_no_endpoint_proof_here
#check R1989DLeanEndpointConcreteLemmaStubs.endpoint_lemma_stub_dependency_grid_to_stub_bank
#check R1989DLeanEndpointConcreteLemmaStubs.endpoint_lemma_stub_dependency_grid_to_first_boundary
#check R1989DLeanEndpointConcreteLemmaStubs.endpoint_lemma_stub_dependency_grid_to_axiom_boundary
#check R1989DLeanEndpointConcreteLemmaStubs.endpoint_lemma_stub_dependency_grid_records_no_endpoint_proof_here
#check R1989DLeanEndpointConcreteLemmaStubs.endpoint_concrete_lemma_stubs_to_actual_li_target
#check R1989DLeanEndpointConcreteLemmaStubs.endpoint_lemma_stub_dependency_grid_to_actual_li_target
#check R1989DLeanEndpointConcreteLemmaStubs.r1989_twenty_eighth_step_records_endpoint_concrete_lemma_stub_bank
#check R1989DLeanEndpointConcreteLemmaStubs.r1989_twenty_eighth_step_records_endpoint_concrete_lemma_dependency_grid
#check R1989DLeanEndpointConcreteLemmaStubs.r1989_twenty_eighth_step_is_stub_bank_not_endpoint_estimate_proof
#check R1989DLeanEndpointConcreteLemmaStubs.r1989_twenty_eighth_step_does_not_claim_rh_formalization
#check R1989DLeanEndpointConcreteLemmaStubs.toy_endpoint_concrete_lemma_stub_bank_to_first_boundary_runs
#check R1989DLeanEndpointConcreteLemmaStubs.toy_endpoint_concrete_lemma_stub_bank_to_axiom_boundary_runs
#check R1989DLeanEndpointConcreteLemmaStubs.toy_endpoint_concrete_lemma_stubs_to_actual_li_target_runs
#check R1989DLeanEndpointConcreteLemmaStubs.toy_endpoint_lemma_stub_dependency_grid_to_stub_bank_runs



/-!
R1990D continuation checks.
These checks refine the R1989D endpoint concrete-lemma stub bank and dependency
grid into a concrete-lemma statement bank and dependency matrix.  The layer
records statement forms only; it does not discharge any endpoint estimate or
any RH-level claim.
-/

#check R1990DLeanEndpointConcreteLemmaStatementBank.EndpointConcreteLemmaStatementStage
#check R1990DLeanEndpointConcreteLemmaStatementBank.EndpointConcreteLemmaStatementKind
#check R1990DLeanEndpointConcreteLemmaStatementBank.EndpointConcreteLemmaStatementItem
#check R1990DLeanEndpointConcreteLemmaStatementBank.MainAnchoredEndpointConcreteLemmaStatementBank
#check R1990DLeanEndpointConcreteLemmaStatementBank.EndpointStatementDependencyKind
#check R1990DLeanEndpointConcreteLemmaStatementBank.EndpointStatementDependencyItem
#check R1990DLeanEndpointConcreteLemmaStatementBank.EndpointStatementDependencyMatrix
#check R1990DLeanEndpointConcreteLemmaStatementBank.endpoint_concrete_lemma_statement_bank_to_stub_grid
#check R1990DLeanEndpointConcreteLemmaStatementBank.endpoint_concrete_lemma_statement_bank_to_stub_bank
#check R1990DLeanEndpointConcreteLemmaStatementBank.endpoint_concrete_lemma_statement_bank_to_first_boundary
#check R1990DLeanEndpointConcreteLemmaStatementBank.endpoint_concrete_lemma_statement_bank_to_axiom_boundary
#check R1990DLeanEndpointConcreteLemmaStatementBank.endpoint_concrete_lemma_statement_bank_records_no_endpoint_proof_here
#check R1990DLeanEndpointConcreteLemmaStatementBank.endpoint_statement_dependency_matrix_to_statement_bank
#check R1990DLeanEndpointConcreteLemmaStatementBank.endpoint_statement_dependency_matrix_to_stub_grid
#check R1990DLeanEndpointConcreteLemmaStatementBank.endpoint_statement_dependency_matrix_to_stub_bank
#check R1990DLeanEndpointConcreteLemmaStatementBank.endpoint_statement_dependency_matrix_to_axiom_boundary
#check R1990DLeanEndpointConcreteLemmaStatementBank.endpoint_statement_dependency_matrix_records_no_endpoint_proof_here
#check R1990DLeanEndpointConcreteLemmaStatementBank.endpoint_concrete_lemma_statement_bank_to_actual_li_target
#check R1990DLeanEndpointConcreteLemmaStatementBank.endpoint_statement_dependency_matrix_to_actual_li_target
#check R1990DLeanEndpointConcreteLemmaStatementBank.r1990_twenty_ninth_step_records_endpoint_concrete_lemma_statement_bank
#check R1990DLeanEndpointConcreteLemmaStatementBank.r1990_twenty_ninth_step_records_endpoint_concrete_lemma_statement_dependency_matrix
#check R1990DLeanEndpointConcreteLemmaStatementBank.r1990_twenty_ninth_step_is_statement_bank_not_endpoint_estimate_proof
#check R1990DLeanEndpointConcreteLemmaStatementBank.r1990_twenty_ninth_step_does_not_claim_rh_formalization
#check R1990DLeanEndpointConcreteLemmaStatementBank.toy_endpoint_concrete_lemma_statement_bank_to_stub_grid_runs
#check R1990DLeanEndpointConcreteLemmaStatementBank.toy_endpoint_concrete_lemma_statement_bank_to_stub_bank_runs
#check R1990DLeanEndpointConcreteLemmaStatementBank.toy_endpoint_concrete_lemma_statement_bank_to_actual_li_target_runs
#check R1990DLeanEndpointConcreteLemmaStatementBank.toy_endpoint_statement_dependency_matrix_to_statement_bank_runs


/-!
R1991D continuation checks.
These checks refine the R1990D endpoint concrete-lemma statement bank and
dependency matrix into a proof-route bank and dependency plan.  The layer
records proof-file routing only; it does not discharge any endpoint estimate or
any RH-level claim.
-/

#check R1991DLeanEndpointConcreteProofRouteBank.EndpointConcreteProofRouteStage
#check R1991DLeanEndpointConcreteProofRouteBank.EndpointConcreteProofRouteKind
#check R1991DLeanEndpointConcreteProofRouteBank.EndpointConcreteProofRouteItem
#check R1991DLeanEndpointConcreteProofRouteBank.MainAnchoredEndpointConcreteProofRouteBank
#check R1991DLeanEndpointConcreteProofRouteBank.EndpointProofRouteDependencyKind
#check R1991DLeanEndpointConcreteProofRouteBank.EndpointProofRouteDependencyItem
#check R1991DLeanEndpointConcreteProofRouteBank.EndpointProofRouteDependencyPlan
#check R1991DLeanEndpointConcreteProofRouteBank.endpoint_concrete_proof_route_bank_to_statement_dependency_matrix
#check R1991DLeanEndpointConcreteProofRouteBank.endpoint_concrete_proof_route_bank_to_statement_bank
#check R1991DLeanEndpointConcreteProofRouteBank.endpoint_concrete_proof_route_bank_to_stub_grid
#check R1991DLeanEndpointConcreteProofRouteBank.endpoint_concrete_proof_route_bank_to_axiom_boundary
#check R1991DLeanEndpointConcreteProofRouteBank.endpoint_concrete_proof_route_bank_records_no_endpoint_proof_here
#check R1991DLeanEndpointConcreteProofRouteBank.endpoint_proof_route_dependency_plan_to_route_bank
#check R1991DLeanEndpointConcreteProofRouteBank.endpoint_proof_route_dependency_plan_to_statement_dependency_matrix
#check R1991DLeanEndpointConcreteProofRouteBank.endpoint_proof_route_dependency_plan_to_statement_bank
#check R1991DLeanEndpointConcreteProofRouteBank.endpoint_proof_route_dependency_plan_records_no_endpoint_proof_here
#check R1991DLeanEndpointConcreteProofRouteBank.endpoint_concrete_proof_route_bank_to_actual_li_target
#check R1991DLeanEndpointConcreteProofRouteBank.endpoint_proof_route_dependency_plan_to_actual_li_target
#check R1991DLeanEndpointConcreteProofRouteBank.r1991_thirtieth_step_records_endpoint_concrete_proof_route_bank
#check R1991DLeanEndpointConcreteProofRouteBank.r1991_thirtieth_step_records_endpoint_proof_route_dependency_plan
#check R1991DLeanEndpointConcreteProofRouteBank.r1991_thirtieth_step_is_route_bank_not_endpoint_estimate_proof
#check R1991DLeanEndpointConcreteProofRouteBank.r1991_thirtieth_step_does_not_claim_rh_formalization
#check R1991DLeanEndpointConcreteProofRouteBank.toy_endpoint_concrete_proof_route_bank_to_statement_dependency_matrix_runs
#check R1991DLeanEndpointConcreteProofRouteBank.toy_endpoint_concrete_proof_route_bank_to_statement_bank_runs
#check R1991DLeanEndpointConcreteProofRouteBank.toy_endpoint_concrete_proof_route_bank_to_actual_li_target_runs
#check R1991DLeanEndpointConcreteProofRouteBank.toy_endpoint_proof_route_dependency_plan_to_route_bank_runs
