import R2017DLeanEndpointFirstExecutableAttemptShellBoundary
import R2018DLeanEndpointFirstExecutableAttemptInputSlots.EndpointFirstExecutableAttemptInputSlots
import R2018DLeanEndpointFirstExecutableAttemptInputSlots.EndpointFirstExecutableAttemptInputDependencyAudit
import R2018DLeanEndpointFirstExecutableAttemptInputSlots.EndpointFirstExecutableAttemptInputBridge
import R2018DLeanEndpointFirstExecutableAttemptInputSlots.ToyEndpointFirstExecutableAttemptInputSlots
