import R2097DLeanConcreteRealAbelLimitTheorem.ConcreteRealAbelLimitTheorem

namespace R2097DLeanConcreteRealAbelLimitTheorem

#check real_abel_average_tendsto_of_partial_sums
#check ConcreteRealAbelLimitWitness
#check concreteRealAbelLimitWitness

end R2097DLeanConcreteRealAbelLimitTheorem
