import R2103DLeanLiPhaseNormalForm.LiPhaseNormalForm

#check R2103DLeanLiPhaseNormalForm.liPhaseAmplitude
#check R2103DLeanLiPhaseNormalForm.liPhaseNormalForm
#check R2103DLeanLiPhaseNormalForm.li_phase_amplitude_nonneg
#check R2103DLeanLiPhaseNormalForm.abs_li_phase_normal_form_le_amplitude
#check R2103DLeanLiPhaseNormalForm.actual_li_rational_amplitude_eq_phase_amplitude
#check R2103DLeanLiPhaseNormalForm.actual_li_kernel_eq_phase_normal_form
#check R2103DLeanLiPhaseNormalForm.LiPhaseNormalFormWitness
#check R2103DLeanLiPhaseNormalForm.liPhaseNormalFormWitness

#print axioms R2103DLeanLiPhaseNormalForm.li_phase_amplitude_nonneg
#print axioms R2103DLeanLiPhaseNormalForm.abs_li_phase_normal_form_le_amplitude
#print axioms R2103DLeanLiPhaseNormalForm.actual_li_rational_amplitude_eq_phase_amplitude
#print axioms R2103DLeanLiPhaseNormalForm.actual_li_kernel_eq_phase_normal_form
