import R2106DLeanFiniteLiBoundaryIntegration.FiniteLiBoundaryIntegration

#check R2106DLeanFiniteLiBoundaryIntegration.finiteLiBoundaryIntegral
#check R2106DLeanFiniteLiBoundaryIntegration.finiteLiBoundaryTerm
#check R2106DLeanFiniteLiBoundaryIntegration.finiteLiInteriorCorrection
#check R2106DLeanFiniteLiBoundaryIntegration.finite_li_boundary_integral_by_parts
#check R2106DLeanFiniteLiBoundaryIntegration.FiniteLiBoundaryIntegrationWitness
#check R2106DLeanFiniteLiBoundaryIntegration.finiteLiBoundaryIntegrationWitness

#print axioms R2106DLeanFiniteLiBoundaryIntegration.finite_li_boundary_integral_by_parts
#print axioms R2106DLeanFiniteLiBoundaryIntegration.finiteLiBoundaryIntegrationWitness
