import R2104DLeanCanonicalLiPhaseInverse.CanonicalLiPhaseInverse

#check R2104DLeanCanonicalLiPhaseInverse.canonicalLiPhaseInverse
#check R2104DLeanCanonicalLiPhaseInverse.canonicalLiCellBoundary
#check R2104DLeanCanonicalLiPhaseInverse.canonical_li_cell_boundary_eq
#check R2104DLeanCanonicalLiPhaseInverse.canonical_li_phase_inverse_pos
#check R2104DLeanCanonicalLiPhaseInverse.canonical_li_phase_inverse_left
#check R2104DLeanCanonicalLiPhaseInverse.canonical_li_phase_inverse_right
#check R2104DLeanCanonicalLiPhaseInverse.actual_li_kernel_at_phase_inverse
#check R2104DLeanCanonicalLiPhaseInverse.CanonicalLiPhaseInverseWitness
#check R2104DLeanCanonicalLiPhaseInverse.canonicalLiPhaseInverseWitness

#print axioms R2104DLeanCanonicalLiPhaseInverse.canonical_li_phase_inverse_pos
#print axioms R2104DLeanCanonicalLiPhaseInverse.canonical_li_phase_inverse_left
#print axioms R2104DLeanCanonicalLiPhaseInverse.canonical_li_phase_inverse_right
#print axioms R2104DLeanCanonicalLiPhaseInverse.actual_li_kernel_at_phase_inverse
