import R2086DLeanEndpointFirstConcreteObligationNonCircularAnalyticEvidence.EndpointFirstConcreteObligationNonCircularAnalyticEvidence

namespace R2086DLeanEndpointFirstConcreteObligationNonCircularAnalyticEvidence

#check NonCircularAnalyticEvidence
#check NonCircularAnalyticEvidence.mk
#check non_circular_analytic_evidence_has_no_target_assumption

end R2086DLeanEndpointFirstConcreteObligationNonCircularAnalyticEvidence
