import R2084DLeanEndpointFirstConcreteObligationEndpointDependencyClosureWitness.EndpointFirstConcreteObligationEndpointDependencyClosureWitness

namespace R2084DLeanEndpointFirstConcreteObligationEndpointDependencyClosureWitness

#check EndpointDependencyClosureWitness
#check EndpointDependencyClosureExists
#check endpoint_first_concrete_obligation_endpoint_dependency_closure_witness_to_finalization_evidence
#check endpoint_first_concrete_obligation_endpoint_dependency_closure_witness_preserves_certificate_statement

end R2084DLeanEndpointFirstConcreteObligationEndpointDependencyClosureWitness
