import R2107DLeanSmoothZeroCountingDensity.SmoothZeroCountingDensity

#check R2107DLeanSmoothZeroCountingDensity.smoothZeroCountingMain
#check R2107DLeanSmoothZeroCountingDensity.smoothZeroCountingDensity
#check R2107DLeanSmoothZeroCountingDensity.smooth_zero_counting_argument_pos
#check R2107DLeanSmoothZeroCountingDensity.hasDerivAt_smooth_zero_counting_main
#check R2107DLeanSmoothZeroCountingDensity.differentiableAt_smooth_zero_counting_main
#check R2107DLeanSmoothZeroCountingDensity.deriv_smooth_zero_counting_main
#check R2107DLeanSmoothZeroCountingDensity.SmoothZeroCountingDensityWitness
#check R2107DLeanSmoothZeroCountingDensity.smoothZeroCountingDensityWitness

#print axioms R2107DLeanSmoothZeroCountingDensity.hasDerivAt_smooth_zero_counting_main
#print axioms R2107DLeanSmoothZeroCountingDensity.deriv_smooth_zero_counting_main
#print axioms R2107DLeanSmoothZeroCountingDensity.smoothZeroCountingDensityWitness
