import R2087DLeanEndpointFirstConcreteObligationActualLiTargetDischarge.EndpointFirstConcreteObligationActualLiTargetDischarge

namespace R2087DLeanEndpointFirstConcreteObligationActualLiTargetDischarge

#check ActualLiTargetDischargeStatement
#check actual_li_target_from_nine_analytic_components
#check endpoint_first_concrete_obligation_actual_li_target_discharge
#check endpoint_first_concrete_obligation_actual_li_target_without_dependency_closure

end R2087DLeanEndpointFirstConcreteObligationActualLiTargetDischarge
