import R2082DLeanEndpointFirstConcreteObligationEndpointTheoremFinalizationEvidence.EndpointFirstConcreteObligationEndpointTheoremFinalizationEvidence

namespace R2082DLeanEndpointFirstConcreteObligationEndpointTheoremFinalizationEvidence

#check EndpointTheoremFinalizationEvidence
#check endpoint_first_concrete_obligation_endpoint_theorem_finalization_evidence
#check endpoint_first_concrete_obligation_endpoint_theorem_finalization_evidence_constructed
#check endpoint_first_concrete_obligation_endpoint_theorem_finalization_evidence_to_actual_li_target
#check endpoint_first_concrete_obligation_endpoint_theorem_finalization_evidence_to_certificate_statement
#check endpoint_first_concrete_obligation_endpoint_theorem_finalization_evidence_to_export_proof

end R2082DLeanEndpointFirstConcreteObligationEndpointTheoremFinalizationEvidence
