import R2082DLeanEndpointFirstConcreteObligationEndpointTheoremFinalizationEvidence.EndpointFirstConcreteObligationEndpointTheoremFinalizationEvidence

namespace R2082DLeanEndpointFirstConcreteObligationEndpointTheoremFinalizationEvidence

def endpoint_theorem_finalization_evidence_bridge_to_actual_li_target :=
  @endpoint_first_concrete_obligation_endpoint_theorem_finalization_evidence_to_actual_li_target

def endpoint_theorem_finalization_evidence_bridge_to_certificate_statement :=
  @endpoint_first_concrete_obligation_endpoint_theorem_finalization_evidence_to_certificate_statement

end R2082DLeanEndpointFirstConcreteObligationEndpointTheoremFinalizationEvidence
