import R2081DLeanEndpointFirstConcreteObligationEndpointTheoremFinalizationGate.EndpointFirstConcreteObligationEndpointTheoremFinalizationGate

namespace R2081DLeanEndpointFirstConcreteObligationEndpointTheoremFinalizationGate

theorem endpoint_theorem_finalization_gate_bridge_replay_input_available :
    endpoint_first_concrete_obligation_endpoint_theorem_finalization_gate_record.certificateReplayInputAvailableHere = true :=
  endpoint_first_concrete_obligation_endpoint_theorem_finalization_gate_replay_input_available

theorem endpoint_theorem_finalization_gate_bridge_result_recorded :
    endpoint_first_concrete_obligation_endpoint_theorem_finalization_gate_record.endpointTheoremFinalizationGateResultRecordedHere = true :=
  endpoint_first_concrete_obligation_endpoint_theorem_finalization_gate_result_recorded

theorem endpoint_theorem_finalization_gate_bridge_keeps_finalization_open :
    endpoint_first_concrete_obligation_endpoint_theorem_finalization_gate_record.endpointTheoremFinalizedHere = false :=
  endpoint_first_concrete_obligation_endpoint_theorem_finalization_gate_keeps_theorem_unfinalized

end R2081DLeanEndpointFirstConcreteObligationEndpointTheoremFinalizationGate
