import R2081DLeanEndpointFirstConcreteObligationEndpointTheoremFinalizationGate.EndpointFirstConcreteObligationEndpointTheoremFinalizationGate

namespace R2081DLeanEndpointFirstConcreteObligationEndpointTheoremFinalizationGate

#check endpoint_first_concrete_obligation_endpoint_theorem_finalization_gate_to_actual_li_target
#check endpoint_first_concrete_obligation_endpoint_theorem_finalization_gate_statement
#check endpoint_first_concrete_obligation_endpoint_theorem_finalization_gate_checked_candidate
#check endpoint_first_concrete_obligation_endpoint_theorem_finalization_gate_replay_record
#check endpoint_first_concrete_obligation_endpoint_theorem_finalization_gate_record
#check endpoint_first_concrete_obligation_endpoint_theorem_finalization_gate_result_recorded
#check endpoint_first_concrete_obligation_endpoint_theorem_finalization_gate_keeps_theorem_unfinalized

theorem endpoint_theorem_finalization_gate_dependency_audit :
    endpoint_first_concrete_obligation_endpoint_theorem_finalization_gate_record.endpointTheoremFinalizationGateExecutedHere = true :=
  endpoint_first_concrete_obligation_endpoint_theorem_finalization_gate_executed

end R2081DLeanEndpointFirstConcreteObligationEndpointTheoremFinalizationGate
