import R2080DLeanEndpointFirstConcreteObligationEndpointCertificateReplay.EndpointFirstConcreteObligationEndpointCertificateReplay

namespace R2080DLeanEndpointFirstConcreteObligationEndpointCertificateReplay

#check endpoint_first_concrete_obligation_endpoint_certificate_replay_to_actual_li_target
#check endpoint_first_concrete_obligation_endpoint_certificate_replay_statement
#check endpoint_first_concrete_obligation_endpoint_certificate_replay_checked_candidate
#check endpoint_first_concrete_obligation_endpoint_certificate_replay_export_packet
#check endpoint_first_concrete_obligation_endpoint_certificate_replay_record
#check endpoint_first_concrete_obligation_endpoint_certificate_replay_result_recorded
#check endpoint_first_concrete_obligation_endpoint_certificate_replay_keeps_certificate_incomplete

theorem endpoint_certificate_replay_dependency_audit :
    endpoint_first_concrete_obligation_endpoint_certificate_replay_record.endpointCertificateReplayExecutedHere = true :=
  endpoint_first_concrete_obligation_endpoint_certificate_replay_executed

end R2080DLeanEndpointFirstConcreteObligationEndpointCertificateReplay
