import R2080DLeanEndpointFirstConcreteObligationEndpointCertificateReplay.EndpointFirstConcreteObligationEndpointCertificateReplay

namespace R2080DLeanEndpointFirstConcreteObligationEndpointCertificateReplay

theorem endpoint_certificate_replay_bridge_packet_available :
    endpoint_first_concrete_obligation_endpoint_certificate_replay_record.exportPacketAvailableHere = true :=
  endpoint_first_concrete_obligation_endpoint_certificate_replay_packet_available

theorem endpoint_certificate_replay_bridge_result_recorded :
    endpoint_first_concrete_obligation_endpoint_certificate_replay_record.endpointCertificateReplayResultRecordedHere = true :=
  endpoint_first_concrete_obligation_endpoint_certificate_replay_result_recorded

theorem endpoint_certificate_replay_bridge_keeps_acceptance_open :
    endpoint_first_concrete_obligation_endpoint_certificate_replay_record.endpointCertificateReplayAcceptedHere = false :=
  endpoint_first_concrete_obligation_endpoint_certificate_replay_not_yet_accepted

end R2080DLeanEndpointFirstConcreteObligationEndpointCertificateReplay
