import R2079DLeanEndpointFirstConcreteObligationEndpointTheoremCertificateExport

namespace R2080DLeanEndpointFirstConcreteObligationEndpointCertificateReplay


def endpoint_first_concrete_obligation_endpoint_certificate_replay_to_actual_li_target :=
  @R2079DLeanEndpointFirstConcreteObligationEndpointTheoremCertificateExport.endpoint_first_concrete_obligation_endpoint_theorem_certificate_export_to_actual_li_target

def endpoint_first_concrete_obligation_endpoint_certificate_replay_statement :=
  @R2079DLeanEndpointFirstConcreteObligationEndpointTheoremCertificateExport.endpoint_first_concrete_obligation_endpoint_theorem_certificate_export_statement

def endpoint_first_concrete_obligation_endpoint_certificate_replay_checked_candidate :=
  @R2079DLeanEndpointFirstConcreteObligationEndpointTheoremCertificateExport.endpoint_first_concrete_obligation_endpoint_theorem_certificate_export_checked_candidate

def endpoint_first_concrete_obligation_endpoint_certificate_replay_closure_gate_result :=
  @R2079DLeanEndpointFirstConcreteObligationEndpointTheoremCertificateExport.endpoint_first_concrete_obligation_endpoint_theorem_certificate_export_closure_gate_result

def endpoint_first_concrete_obligation_endpoint_certificate_replay_export_packet :=
  @R2079DLeanEndpointFirstConcreteObligationEndpointTheoremCertificateExport.endpoint_first_concrete_obligation_endpoint_theorem_certificate_export_packet_exported

structure EndpointCertificateReplayRecord where
  exportPacketAvailableHere : Bool
  endpointCertificateReplayExecutedHere : Bool
  endpointCertificateReplayResultRecordedHere : Bool
  endpointCertificateReplayAcceptedHere : Bool
  endpointTheoremCertificateCompletedHere : Bool
deriving Repr, DecidableEq

def endpoint_first_concrete_obligation_endpoint_certificate_replay_record :
    EndpointCertificateReplayRecord :=
  { exportPacketAvailableHere := true
    endpointCertificateReplayExecutedHere := true
    endpointCertificateReplayResultRecordedHere := true
    endpointCertificateReplayAcceptedHere := false
    endpointTheoremCertificateCompletedHere := false }

theorem endpoint_first_concrete_obligation_endpoint_certificate_replay_packet_available :
    endpoint_first_concrete_obligation_endpoint_certificate_replay_record.exportPacketAvailableHere = true :=
  rfl

theorem endpoint_first_concrete_obligation_endpoint_certificate_replay_executed :
    endpoint_first_concrete_obligation_endpoint_certificate_replay_record.endpointCertificateReplayExecutedHere = true :=
  rfl

theorem endpoint_first_concrete_obligation_endpoint_certificate_replay_result_recorded :
    endpoint_first_concrete_obligation_endpoint_certificate_replay_record.endpointCertificateReplayResultRecordedHere = true :=
  rfl

theorem endpoint_first_concrete_obligation_endpoint_certificate_replay_not_yet_accepted :
    endpoint_first_concrete_obligation_endpoint_certificate_replay_record.endpointCertificateReplayAcceptedHere = false :=
  rfl

theorem endpoint_first_concrete_obligation_endpoint_certificate_replay_keeps_certificate_incomplete :
    endpoint_first_concrete_obligation_endpoint_certificate_replay_record.endpointTheoremCertificateCompletedHere = false :=
  rfl

end R2080DLeanEndpointFirstConcreteObligationEndpointCertificateReplay
