import R2085DLeanEndpointFirstConcreteObligationEndpointClosedTargetExtraction.EndpointFirstConcreteObligationEndpointClosedTargetExtraction

namespace R2085DLeanEndpointFirstConcreteObligationEndpointClosedTargetExtraction

#check EndpointClosedTargetStatement
#check endpoint_first_concrete_obligation_endpoint_closed_target_from_witness
#check endpoint_first_concrete_obligation_endpoint_closed_target_extraction
#check endpoint_first_concrete_obligation_endpoint_closed_target_preserves_certificate_statement

end R2085DLeanEndpointFirstConcreteObligationEndpointClosedTargetExtraction
